version: '3.4'
services:
  prysm-witti-validator.dnp.dappnode.eth:
    image: 'prysm-witti-validator.dnp.dappnode.eth:1.0.2'
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        - VERSION=v1.0.0-alpha.6
    volumes:
      - 'logs:/var/log'
      - 'data:/root/.config/ethereum2/'
      - 'db-api:/app/db-api'
    restart: always
    environment:
      - PASSWORD=
      - GRAFFITI=prylabs-witi-validator-dappnode
      - VERBOSITY=info
      - LOG_LEVEL=
      - EXTRA_OPTS=--enable-account-metrics
      - 'BEACON_GRPC_URL=prysm-witti-beacon-chain.dappnode:4000'
      - 'BEACON_GRPC_GATEWAY_URL=http://prysm-witti-beacon-chain.dappnode:4001'
      - 'WEB3PROVIDER=https://goerli.dappnode.net'
volumes:
  data: {}
  db-api: {}
  logs: {}
